package pl.romcio.driperska.match.domain;

public enum MatchEventType {
    CREATED,
    TEAMS_DRAWN,
    DRAW_CONFIRMED,
    RIOT_LOBBY_CREATED,
    PLAYER_REPLACED,
    MATCH_STARTED,
    RIOT_CALLBACK_RECEIVED,
    RIOT_RESULTS_IMPORTED,
    RIOT_IMPORT_FAILED,
    RESULTS_SUBMITTED,
    RESULTS_EDITED,
    APPROVED,
    REJECTED,
    REOPENED,
    CANCELLED
}
