export interface ReleaseNote {
  version: string;
  date: string;
  title: string;
  changes: string[];
}

/**
 * Public patch notes. Add the newest release at the top; the home page renders
 * this list automatically.
 */
export const RELEASES: ReleaseNote[] = [
  {
    version: 'v0.4.8',
    date: '2026-07-29',
    title: 'Zgoda na reklamy',
    changes: [
      'Przy pierwszym wejściu pojawia się panel zgody na reklamy: pełna zgoda, tylko niespersonalizowane albo brak reklam. Bez odpowiedzi skrypt reklamowy nie jest w ogóle pobierany.',
      'Odmowa jest jednym kliknięciem i wygląda tak samo jak zgoda — panel nie zasłania też strony, więc ranking, mecze i draft działają identycznie w każdym wariancie.',
      'Decyzję zmienisz w każdej chwili linkiem „Prywatność i reklamy” w stopce albo „Ustawienia” przy dowolnym bloku reklamowym.',
      'Pytamy tylko o reklamy — strona nie ma analityki ani wtyczek społecznościowych, więc nie ma o co więcej pytać.',
    ],
  },
  {
    version: 'v0.4.7',
    date: '2026-07-29',
    title: 'Archiwum meczów, ekran ładowania i logo w jednej wersji',
    changes: [
      'Nowa zakładka „Mecze” z pełnym archiwum — wcześniej widoczne było tylko sześć ostatnich wyników na stronie głównej.',
      'Strona wita ekranem ładowania w kolorach ligi, który w tle buforuje klipy z zagrywek, żeby hero startowało od razu. Otwiera się najpóźniej po 6 sekundach, niezależnie od łącza.',
      'Logo jest teraz jedno i to samo w każdym miejscu — ten sam znak, co w nawigacji.',
      'Pojawiły się nieliczne, wyciszone bloki reklamowe na stronie głównej i w panelu gracza. Nie ma ich nad zgięciem strony, w drafcie ani w panelu admina.',
    ],
  },
  {
    version: 'v0.4.6',
    date: '2026-07-29',
    title: 'Logo ligi i blokady pól przy odczycie ze screenshotów',
    changes: [
      'Liga ma własne logo — monogram DL w czterech wariantach, w kolorach strony. Znak wchodzi na navbary, stronę główną, ekran logowania i favicon.',
      'Karty wyników i patch notes wysyłane na Discorda są teraz podpisane logo w nagłówku.',
      'Przy wpisywaniu wyniku każde pole ma małą kłódkę: zablokowane pole nie zostanie nadpisane, gdy dorzucisz kolejny screenshot. Kłódka odsłania się dopiero po najechaniu na pole, żeby nie zasłaniała liczb.',
      'Blokady obejmują pozycję, championa i wszystkie statystyki każdego gracza, a także zwycięską stronę i czas gry. Do tego licznik zablokowanych pól oraz „Zablokuj / Odblokuj wszystko”.',
    ],
  },
  {
    version: 'v0.4.5',
    date: '2026-07-28',
    title: 'Konfiguracja i AI z panelu, test draftu',
    changes: [
      'Klucze API, modele AI, kanały Discorda i czasy draftu zmieniasz w panelu admina — bez restartu i bez edycji .env na serwerze.',
      'Nowa zakładka „AI”: podgląd aktywnego modelu, lista modeli z konta Ollama i przycisk „Testuj”, który sprawdza model przed przełączeniem.',
      'Nowa zakładka „Test draftu”: pełna symulacja draftu turniejowego z botami — ta sama plansza, dźwięki i zegar, co u graczy. Nic nie jest zapisywane.',
      'Zakładka „Mecze” w panelu admina jest teraz zwijanym menu.',
      'Karty ostatnich wyników na stronie głównej pokazują ikony postaci i nicki obu drużyn, więc od razu widać, o który mecz chodzi.',
    ],
  },
  {
    version: 'v0.4.4',
    date: '2026-07-28',
    title: 'Porównywalny PR i MVP między rolami',
    changes: [
      'Pozycja nadal określa bazę porównania, ale końcowe wagi są takie same dla wszystkich ról — dobry wynik 0–1 ma identyczną wartość na TOP-ie, ADC i pozostałych pozycjach.',
      'Nowe wagi ligi: KDA 35%, KP 20%, CS/min 10%, damage/min 25%, efektywność 5% i vision/min 5%.',
      'Usunięto sytuację, w której lepsze znormalizowane KDA dawało mniej punktów tylko z powodu innej pozycji.',
      'Historyczne mecze zostaną automatycznie przeliczone do nowych zasad.',
    ],
  },
  {
    version: 'v0.4.3',
    date: '2026-07-28',
    title: 'Aktywność i bonusy za KDA',
    changes: [
      'MVP mocniej odzwierciedla ten konkretny mecz: historia pozycji ma maksymalnie 50% wpływu na PR, a bezpośrednie porównanie rywali tej roli zawsze co najmniej 50%.',
      'Każdy rozegrany mecz dodaje +0,10 do wyniku rankingowego, maksymalnie +2,00 po 20 meczach — dalsza gra poprawia pozycję, ale jakość występów nadal jest najważniejsza.',
      'Najlepsze KDA w meczu daje +1 LP; remis oznacza współdzielony bonus.',
      'Perfect KDA daje +1 LP za 0 śmierci i co najmniej jedno zabójstwo lub asystę. Wynik 0/0/0 nie dostaje bonusu.',
      'Bonusy za najlepsze KDA i perfect KDA stackują się ze sobą oraz z MVP albo ACE.',
      'Historyczne sezony zostaną automatycznie przeliczone po wdrożeniu.',
      'Patch notes na Discordzie trafiają wyłącznie na dedykowany, jawnie skonfigurowany kanał.',
      'Dźwięk draftu odblokowuje się po pierwszej interakcji w aplikacji, a gracz dostaje przypomnienie o swojej turze przy 10 sekundach.',
    ],
  },
  {
    version: 'v0.4.2',
    date: '2026-07-28',
    title: 'Naprawione widoki meczów gracza',
    changes: [
      'Naprawiono błąd 500, który na PostgreSQL mógł blokować aktywne lobby oraz listę meczów oczekujących na ocenę.',
      'Pobieranie meczów z puli gracza zachowuje prawidłową kolejność po dacie rozpoczęcia i nie generuje już niezgodnego zapytania SQL.',
      'Naprawiono start po aktualizacji z 0.4.1: automatyczne przeliczenie rankingu nie wpada już w konflikt istniejących statystyk sezonowych.',
    ],
  },
  {
    version: 'v0.4.1',
    date: '2026-07-28',
    title: 'PR v2, uczciwsze LP i pełne ACE',
    changes: [
      'PR v2 porównuje występ z wcześniejszymi graczami na tej samej pozycji. Wagi KDA pozostały bez zmian.',
      'Złoto oceniamy przez efektywność obrażenia/złoto, zamiast nagradzać samo przejmowanie zasobów.',
      'Nowe LP: wygrana +10, przegrana +4, a jakość występu daje od −2 do +3 według przejrzystych progów PR.',
      'MVP daje +3. ACE daje +2 najlepszemu przegranemu od PR 60; MVP i ACE nie stackują bonusów.',
      'Penta, quadra i flawless są nadal osiągnięciami, ale nie wpływają na LP.',
      'Tabela premiuje jakość zamiast samej liczby gier: główny wynik to stabilizowana średnia punktów, a pełna klasyfikacja zaczyna się od 5 meczów.',
      'MMR to teraz czyste Elo — dobry przegrany nie traci więcej MMR przez wysoki PR.',
      'Historyczne sezony zostaną automatycznie przeliczone do nowych zasad po wdrożeniu.',
    ],
  },
  {
    version: 'v0.4.0',
    date: '2026-07-28',
    title: 'Draft na pełny ekran, dźwięki i naprawione listy meczów',
    changes: [
      'Naprawiony błąd, który wywalał wszystkie listy meczów (Pulpit, Akceptacje, lista meczów, licznik w menu zwracały 500).',
      'Draft na cały ekran: obie drużyny, bany, zegar i pula postaci widoczne naraz, bez przewijania. Draft ma teraz własną zakładkę w panelu gracza i włącza się automatycznie, gdy admin go wystartuje.',
      'Zaznaczoną postać widzą wszyscy w lobby — obie drużyny na żywo widzą, co gracz na zegarze zamierza wybrać albo zbanować.',
      'Po upływie czasu postać zawsze się odsłania: jeśli zdążyłeś ją zaznaczyć, licznik zablokuje właśnie ją, a nie losową. Slot nigdy nie zostaje pusty.',
      'Dźwięki w drafcie z suwakiem głośności: „twoja kolej”, lock-in, ban, ostatnie 5 sekund, koniec draftu i muzyka w tle.',
      'Admin może podmienić komuś postać w trakcie draftu (gdy ktoś zablokował złą) — bez przestawiania kolejności picków.',
      'Draft przestał zamierać po odświeżeniu strony: gdy połączenie na żywo padnie, plansza dalej się odświeża, a w nagłówku widać „tryb odświeżania”.',
      'Nowe „Zapamiętaj mnie” przy logowaniu — sesja trwa do wylogowania i wraca sama po restarcie serwera.',
      'Przy utracie połączenia z serwerem pojawia się jasny komunikat i wylogowanie, a po chwili ekran przerwy technicznej.',
      'Loadingi na całej stronie: zamiast pustego ekranu ze spinnerem widać zarys treści, która się właśnie wczytuje.',
      'Przy głosowaniu na obecność widać imiennie listę osób — kto będzie, kto może, a kto nie.',
    ],
  },
  {
    version: 'v0.3.2',
    date: '2026-07-27',
    title: 'Głosowanie na Discordzie i dokładniejsza punktacja',
    changes: [
      'Głosowanie o obecność prosto z Discorda: zaplanowany mecz dostaje kartę z przyciskami „Będę / Nie będę / Może” na osobnym kanale głosowań, a ogłoszenie z @everyone zostaje na kanale ogłoszeń.',
      'Głosy z Discorda liczą się w systemie tak samo jak głosy ze strony — liczą się tylko kliknięcia kont Discord połączonych z graczem, a głos można zmienić klikając ponownie.',
      'Punktacja LP na stronie meczu jest zwijana: od razu widać tylko sumę punktów każdego gracza, a „Szczegóły” rozwijają pełne rozliczenie — ile za co i według jakiego przelicznika.',
      'Rozpis „jak powstało PR”: każda metryka (KDA, udział w killach, CS/min, obrażenia, złoto, wizja) z Twoją wartością, średnią meczu, normą, wagą pozycji i punktami.',
      'Naprawione daty meczów: wszędzie pokazuje się i sortuje po dacie faktycznego startu gry — edycja czy ponowna akceptacja wyniku nie przesuwa już meczu w listach.',
    ],
  },
  {
    version: 'v0.3.1',
    date: '2026-07-23',
    title: 'Opinie graczy i płynniejsze tło',
    changes: [
      'Zagrywki w tle strony głównej płynnie się przenikają — każdy klip pojawia się i znika łagodnym fade in/out.',
      'Na stronie meczu (dla zalogowanych) sekcja „Opinie graczy”: gracz z największą liczbą plusów i ten z największą liczbą minusów, a obok każdego dynamiczny slider z anonimowymi komentarzami o jego grze (pozytywnymi i negatywnymi).',
      'Poprawiony wygląd na telefonach: górne menu strony głównej chowa się pod hamburger, wersja aplikacji pobierana jest z jednego źródła (package.json).',
      'Szybszy i stabilniejszy odczyt wyników ze screenshotów (OCR): wyłączone „myślenie” modelu i dłuższy limit czasu (koniec timeoutów).',
      'Lepsze rozpoznawanie postaci w OCR: mocniejszy model wizyjny (qwen3.5:397b), włączony atlas referencyjny championów (dopasowanie portretu do nazwy), a normalne screenshoty (~0,5 MB) wysyłane są bez kompresji — kompresja rozmazywała małe ikonki i psuła rozpoznawanie.',
      'Na stronie meczu rozpisana punktacja LP: dla każdego gracza widać z czego składają się punkty (baza za wygraną/przegraną, występ = PR ÷ przelicznik, bonusy MVP/ACE/multikill/bez śmierci) i ile wyszło razem.',
      'Draft: rusza dopiero po kliknięciu „Rozpocznij draft” w panelu admina (czas na przejście na Discorda i ustalenie pozycji). Duży, wyraźny napis „TWOJA KOLEJ”, postać najpierw się zaznacza, a przycisk „Lock in” potwierdza wybór. Admin może wstrzymać/wznowić draft (pauza zatrzymuje licznik).',
      'Po rozpoczęciu gry ekran pokazuje pełny skład „kto kim gra” (gracz + jego postać i pozycja) po obu stronach.',
      'Losowanie składów domyślnie w 100% losowe (a nie zbalansowane po MMR, które powtarzało podobne drużyny). Tryb zbalansowany nadal dostępny do wyboru.',
      'Ręczne układanie drużyn: w trybie „Ręcznie” przy tworzeniu meczu można przeciągnąć graczy do slotów ról (TOP/JUNGLE/MID/ADC/SUPPORT) w obu drużynach i ułożyć skład samodzielnie, bez losowania.',
      'Po restarcie serwera wszyscy są automatycznie wylogowywani (koniec ze „starymi” sesjami wiszącymi po aktualizacji).',
      'Gdy nie ma połączenia z serwerem, pojawia się ekran „Przerwa techniczna” i aplikacja sama łączy się ponownie, gdy serwer wróci.',
      'Wyraźniejsze wskaźniki ładowania i komunikaty o błędach na kolejnych ekranach.',
    ],
  },
  {
    version: 'v0.3.0',
    date: '2026-07-23',
    title: 'Draft turniejowy',
    changes: [
      'Nowość: wewnętrzny draft postaci (bany i picki) w kolejności turniejowej LoL — 5 banów i 5 wyborów na drużynę. Bany robi kapitan drużyny, każdy gracz wybiera własną postać w swojej turze.',
      'Każdy krok draftu ma 30-sekundowy licznik widoczny dla wszystkich; po jego upływie przypisywana jest losowa dostępna postać.',
      'Po draftcie gracze mogą zamieniać się w obrębie drużyny pozycją lub postacią — klik strzałki przy graczu, druga osoba akceptuje.',
      'Admin może zresetować draft w dowolnym momencie z panelu kontroli meczu.',
      'Nowy przełącznik „Wsparcie Riot API” w ustawieniach panelu: wyłączony = po zaakceptowaniu składu startuje draft wewnętrzny (bez kodu Riot); włączony = tworzy lobby turniejowe Riot jak dotychczas.',
      'Poprawka: po odświeżeniu strony lub zalogowaniu w trakcie głosowania od razu widać składy i możliwość głosowania (stan dociera natychmiast przez strumień na żywo).',
      'Poprawka: bez wsparcia Riot API nie pokazuje się już niedziałający kod dołączenia do lobby.',
      'Timer głosowania nad składem wydłużony do 60 sekund, z widocznym odliczaniem dla każdego uczestnika.',
      'W draftcie stała kolejność drużyny od góry: kapitan (TOP) → JUNGLE → MID → ADC → SUPPORT; kapitan banuje, a picki idą po kolei z góry na dół (podświetlany jest gracz, którego jest tura).',
      'Panel admina: przycisk „Patch notes na Discord” w Ustawieniach — generuje obrazek z listą zmian i wysyła na kanał patch notes z pingiem @everyone.',
      'Panel gracza: mecze do oceny przeniesione do zakładki „Ocena” z licznikiem oczekujących ocen (jak powiadomienie).',
      'Po wysłaniu wyników mecz jest w panelu gracza oznaczany jako zakończony (znika draft/lobby, zostaje informacja o oczekiwaniu na zamknięcie meczu przez admina).',
      'Panel admina: zakładki pogrupowane — sekcja „Mecze” zbiera listę meczów, nowy mecz, plan meczów i akceptacje.',
      'Naprawione: zatwierdzone mecze od razu znikają z kolejki akceptacji.',
      'Wyłączone cache’owanie strony — koniec z ręcznym Ctrl+F5, aby zobaczyć nową wersję/dane.',
    ],
  },
  {
    version: 'v0.2.8',
    date: '2026-07-22',
    title: 'Zakładki w panelu gracza i poprawka zdjęcia profilowego',
    changes: [
      'Panel gracza podzielony na zakładki: „Dashboard” (losowanie/gra, potwierdzanie obecności i ocena meczu) oraz „Profil i ustawienia” (edycja profilu, ulubieni bohaterowie, zdjęcie i zmiana hasła).',
      'Na publicznym profilu gracza widać teraz jego ulubionych bohaterów.',
      'Naprawiona zmiana zdjęcia profilowego — dało się je ustawić tylko raz; teraz stare zdjęcie jest usuwane, a nowe od razu widoczne (koniec problemu z cache przeglądarki).',
      'Naprawione wgrywanie „Zagrywek” i powtórek — kończyło się błędem „Access Denied” przy większych plikach.',
      'Panel admina: lista meczów zwijana do rozwijanych elementów (dropdown) — zwarta i czytelna.',
      'Poprawione wyświetlanie panelu admina na telefonach — chowane menu (hamburger) zamiast ściśniętego paska zakładek.',
      'Podczas głosowania nad składem każdy widzi, kto jak zagłosował (Gramy / Losuj ponownie / czeka) — na żywo.',
      'Dłuższa sesja logowania — koniec wylogowywania po kilku minutach. Token ważny domyślnie 12 godzin (a odświeżanie utrzymuje sesję do 30 dni).',
    ],
  },
  {
    version: 'v0.2.7',
    date: '2026-07-22',
    title: 'Ładniejsza karta wyniku i poprawki panelu',
    changes: [
      'Obrazek wyniku na Discord wygląda teraz jak tabela z aplikacji: ikony bohaterów, KDA, CS i kolorowe oceny PR.',
      'Naprawiona zakładka „Mecze” (nie ładowała się w nieskończoność).',
      'Pozycję gracza wpisuje się przy wyniku (grana pozycja, nie ulubiona) — edytowalna w formularzu i czytana ze screenshotów.',
      'Na podsumowaniu meczu stała kolejność: TOP, JUNGLE, MID, BOT, SUPPORT.',
      'Post z wynikiem na Discordzie zawiera link do szczegółów meczu.',
      'W panelu gracza mecz znika po zakończeniu — zostaje sama ankieta oceny z informacją, którego meczu dotyczy (data i składy).',
      'Naprawione wgrywanie klipów i powtórek na produkcji — większe limity (do 512 MB przez nginx i backend, klipy do 400 MB) i czytelny komunikat zamiast błędu przy zbyt dużym pliku.',
      'Drobne utwardzenie strumienia na żywo (SSE) — brak wyjątku w logach po wygaśnięciu połączenia.',
      'Godziny wyświetlane w formacie 24-godzinnym i w polskiej strefie czasowej (Europe/Warsaw).',
    ],
  },
  {
    version: 'v0.2.6',
    date: '2026-07-22',
    title: 'Oceny meczu, zmiana hasła, zabezpieczenie logowania',
    changes: [
      'Po meczu zamiast statystyk: opcjonalna ankieta — jeden plus i jeden minus dla wybranych graczy + notatka z uzasadnieniem.',
      'Profil gracza zwalnia się po zakończonym meczu.',
      'Zmiana hasła w ustawieniach konta gracza.',
      'Cloudflare Turnstile na formularzu logowania (ochrona przed botami).',
    ],
  },
  {
    version: 'v0.2.5',
    date: '2026-07-22',
    title: 'Planowanie meczów, diagnostyka i poprawki',
    changes: [
      'Naprawione udostępnianie wyniku na Discord (błąd reactive-streams przy wysyłce obrazka).',
      'Większy limit wgrywanych plików — koniec „request too large” przy powtórkach i screenshotach.',
      'Zakładka „Mecze”: tabela wszystkich meczów z edycją i udostępnianiem z poziomu listy.',
      'Planowanie meczów: termin + zbiorowe ogłoszenie na Discord z linkiem do potwierdzenia obecności; gracze RSVP (Będę / Może / Nie), admin widzi kto potwierdził.',
      'Wyszukiwarka bohaterów po nazwie w edycji profilu.',
      'Zakładka „Diagnostyka”: szybkie testy połączenia z AI (Ollama), Discordem i Riot API.',
    ],
  },
  {
    version: 'v0.2.4',
    date: '2026-07-22',
    title: 'Wyniki ze screenshotów (AI)',
    changes: [
      'Wczytywanie statystyk z ekranu podsumowania LoL przez model wizyjny (Ollama Cloud) — tabela wypełnia się sama.',
      'Można wgrać kilka zrzutów naraz (np. osobne zakładki KDA / obrażenia / wizja); dane łączone są po graczu.',
      'AI dopasowuje graczy po nazwie w grze / Riot ID oraz championy po nazwie — admin sprawdza i poprawia przed wysłaniem.',
      'Rozwiązanie tymczasowe, dopóki nie dostaniemy produkcyjnego dostępu do Riot Tournament API.',
    ],
  },
  {
    version: 'v0.2.3',
    date: '2026-07-22',
    title: 'Deploy, zagrywki i zarządzanie meczami',
    changes: [
      'CI wysyła na serwer gotowe obrazy Dockera i uruchamia je bez nadpisywania serwerowych .env oraz docker-compose.yml.',
      'Najlepsze zagrywki MP4/WebM odtwarzane jako subtelne tło strony głównej, z uploadem w panelu.',
      'Naprawione generowanie obrazka wyniku w Dockerze oraz czytelne błędy i logi integracji Discord.',
      'Lista wszystkich meczów z filtrowaniem, edycją i ponownym udostępnianiem wyniku na Discordzie.',
    ],
  },
  {
    version: 'v0.2.2',
    date: '2026-07-22',
    title: 'Wygoda panelu i diagnostyka Discord',
    changes: [
      'Mecz nie znika po odświeżeniu — sekcja „Mecze w przygotowaniu” na pulpicie prowadzi z powrotem do trwającego meczu.',
      'Przycisk „Anuluj mecz” w panelu kontroli meczu.',
      'Udostępnianie obrazka z wynikiem na Discord dostępne także w kolejce akceptacji.',
      'Czytelne komunikaty, gdy DM na Discord nie dojdzie (Server Members Intent, prywatność odbiorcy, numeryczny User ID).',
      'Ostrzeżenie na ekranie lobby, że kod testowy (stub) nie zadziała w kliencie bez produkcyjnego dostępu Tournament API.',
      'Plik weryfikacyjny riot.txt hostowany w korzeniu domeny (rejestracja Tournament API).',
    ],
  },
  {
    version: 'v0.2.1',
    date: '2026-07-21',
    title: 'Poprawki: Riot, zdjęcia, podsumowanie',
    changes: [
      'Naprawiona integracja Riot — poprawny klaster (americas) i tournament-stub dla kluczy deweloperskich (koniec błędów 403).',
      'Usunięte zbędne zapytanie summoner-v4 (błąd „zasób nie istnieje").',
      'Region ustawiony na EUNE.',
      'Naprawione wgrywanie zdjęć (uprawnienia woluminu w Dockerze).',
      'Edycja danych gracza z panelu admina: Riot ID, Discord, role, imię.',
      'Ręczne rozpoczęcie meczu bez Riot oraz edycja już rozegranych meczów.',
      'Auto-akceptacja składu po 30 s i podgląd głosowania na żywo dla admina.',
      'Oceny (PR/LP) widoczne na podsumowaniu zaraz po wpisaniu wyniku.',
      'Udostępnianie obrazka z wynikiem na Discord i wgrywanie powtórki .rofl.',
      'Podpowiedzi statystyk, wyjaśnienie punktacji i osobna zakładka Patch Notes.',
    ],
  },
  {
    version: 'v0.2',
    date: '2026-07-21',
    title: 'Lobby turniejowe i automatyczne wyniki',
    changes: [
      'Automatyczne tworzenie lobby Riot po zaakceptowaniu składów.',
      'Kod gry i przypisana strona widoczne w strefie każdego uczestnika.',
      'Callback oraz ręczne pobieranie statystyk do kolejki akceptacji.',
      'Wymiana gracza przed startem i ponowne wystawienie bezpiecznego kodu.',
      'Dane logowania wysyłane przez bota Discord z opcją kopiowania i ponownej wysyłki.',
    ],
  },
  {
    version: 'v0.1',
    date: '2026-07-21',
    title: 'Pierwsze losowanie',
    changes: [
      'Konta graczy z losowym hasłem i gotową wiadomością do wysłania na DM.',
      'Losowanie drużyn i stron na żywo z głosowaniem 6/10.',
      'Automatyczny re-roll po pięciu głosach przeciw.',
      'Edycja roli, ulubionych championów, zdjęcia profilowego i linku OP.GG.',
      'Bezpieczne migracje bazy i workflow aktualizacji serwera.',
    ],
  },
];